name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login..."
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin de login"

    - name: Build Docker Image
      run: |
        docker build -t manulc/docker-nest-graphql:0.0.1 .
        # Otra opción es usar el comando "docket tag manulc/docker-nest-graphql:0.0.1 manulc/docker-nest-graphql"
        docker build -t manulc/docker-nest-graphql .

    - name: Push Docker Image
      run: |
        docker push manulc/docker-nest-graphql:0.0.1
        docker push manulc/docker-nest-graphql
      
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
